<?php
/* =====================================================================
   BLOG POSTS — the list of every post. One entry per post.

   To add a post:
     1. Add an entry below. The key is the slug = the file name = the URL:
          'sliding-wardrobe-designs'  →  /blogs/sliding-wardrobe-designs.php  →  enteriors.in/blogs/sliding-wardrobe-designs/
     2. Copy _templates/blog-post.php to /blogs/<slug>.php and write the article.
     3. Put the images in /assets/blogs/<folder>/  (hero.jpg|png|webp = main image).

   Required   title, description, category, folder, hero_alt, date
   Optional   location   place the post is about (shown beside the category, used in schema)
              pillar     key of the parent pillar in nav.php, e.g. 'modular-kitchen' — adds the "part of" link
              seo_title  shorter Google title          updated    last edit, YYYY-MM-DD
              author     key from AUTHORS in config    draft      true = visible on staging only
              canonical  '/main/page/' when the post repeats a main guide: Google then counts the main
                         page only (no two pages competing for one search), and the post stays out of
                         the sitemap and llms.txt. The migrated older versions use this.
   Extras such as the quick answer, FAQ and related links are set at the top of the post file itself.
   ===================================================================== */
$POSTS = [

  /* MIGRATED-START — written by tools/migrate.php on 2026-10-04 */
  'kitchen-renovation-cost' => [
    'title'       => 'Kitchen Renovation Cost in India: What You Actually Pay',
    'seo_title'   => 'Kitchen Renovation Cost in India (2026)',
    'description' => 'What a kitchen renovation costs in India in 2026: demolition, plumbing, electrical, cabinets, countertop and appliances, with budgets by kitchen size.',
    'category'    => 'Cost',
    'pillar'      => 'cost',
    'folder'      => 'kitchen-renovation-cost',
    'hero_alt'    => 'Kitchen Renovation Cost in India: What You Actually Pay',
    'date'        => '2026-06-11',
    'updated'     => '2026-10-04',
  ],
  'wallpaper-cost-per-sq-ft' => [
    'title'       => 'Wallpaper Cost Per Square Foot in India — The Only Guide You Need',
    'seo_title'   => 'Wallpaper Cost per Sq Ft in India (2026)',
    'description' => 'Wallpaper cost per sq ft in India in 2026: vinyl, non-woven and fabric types, brands, installation, room-wise picks and wallpaper vs paint costs.',
    'category'    => 'Cost',
    'pillar'      => 'cost',
    'folder'      => 'wallpaper-cost-per-sq-ft',
    'hero_alt'    => 'Wallpaper Cost Per Square Foot in India — The Only Guide You Need',
    'date'        => '2026-06-11',
    'updated'     => '2026-10-04',
  ],
  'hidden-costs-home-interiors' => [
    'title'       => 'Hidden Costs in Home Interiors: What Most Homeowners Discover Too Late',
    'seo_title'   => 'Hidden Costs in Home Interiors',
    'description' => 'The hidden costs in home interiors that push budgets over: GST, electrical, civil and plumbing work, society charges, design fees, and how to plan for them.',
    'category'    => 'Cost',
    'pillar'      => 'cost',
    'folder'      => 'hidden-costs-home-interiors',
    'hero_alt'    => 'Hidden Costs in Home Interiors: What Most Homeowners Discover Too Late',
    'date'        => '2026-06-19',
    'updated'     => '2026-10-04',
  ],
  '2-bhk-interior-cost-breakdown' => [
    'title'       => '2 BHK Interior Design Cost: 800 to 1,500 Sq Ft, Item by Item',
    'seo_title'   => '2 BHK Interior Cost Breakdown (2026)',
    'description' => '2 BHK interior cost for 800–1,500 sq ft homes: plywood types, modular kitchen, wardrobes, flooring, labour and GST, item by item for 2026.',
    'category'    => 'Cost',
    'pillar'      => 'cost',
    'folder'      => '2-bhk-interior-cost-breakdown',
    'hero_alt'    => '2 BHK Interior Design Cost: 800 to 1,500 Sq Ft, Item by Item',
    'date'        => '2026-06-10',
    'updated'     => '2026-10-04',
    'canonical'   => '/cost/2-bhk-interior-cost/',
  ],
  '3-bhk-interior-budget-planning' => [
    'title'       => '3 BHK Interior Cost Calculator & Budget Planning Guide',
    'seo_title'   => '3 BHK Interior Budget Planning (2026)',
    'description' => 'Plan your 3 BHK interior budget with our free cost calculator. Get room-wise breakdowns, material cost comparisons, and expert tips to save money on interiors.',
    'category'    => 'Cost',
    'pillar'      => 'cost',
    'folder'      => '3-bhk-interior-budget-planning',
    'hero_alt'    => '3 BHK Interior Cost Calculator & Budget Planning Guide',
    'date'        => '2026-06-14',
    'updated'     => '2026-10-04',
    'canonical'   => '/cost/3-bhk-interior-cost/',
  ],
  'acrylic-vs-laminate-complete-comparison' => [
    'title'       => 'Acrylic vs Laminate: The Complete Comparison',
    'seo_title'   => 'Acrylic vs Laminate: Complete Comparison',
    'description' => 'Acrylic vs laminate compared on durability, scratches, cost, cleaning, moisture, UV stability and lifespan, with the right choice for each room.',
    'category'    => 'Materials',
    'pillar'      => 'materials',
    'folder'      => 'acrylic-vs-laminate-complete-comparison',
    'hero_alt'    => 'Acrylic vs Laminate: The Complete Comparison',
    'date'        => '2024-01-01',
    'updated'     => '2026-10-04',
    'canonical'   => '/compare/acrylic-vs-laminate/',
  ],
  'interior-material-brands-india' => [
    'title'       => 'Interior Material Brands in India: Every Brand That Goes Into a Well-Built Home',
    'seo_title'   => 'Best Interior Material Brands in India 2026',
    'description' => 'The interior material brands used in Indian homes: plywood, laminates, hardware, handles, channels, acrylic, wall panels and glass, and how to choose.',
    'category'    => 'Materials',
    'pillar'      => 'materials',
    'folder'      => 'interior-material-brands-india',
    'hero_alt'    => 'Interior Material Brands in India: Every Brand That Goes Into a Well-Built Home',
    'date'        => '2025-06-11',
    'updated'     => '2026-10-04',
  ],
  'acrylic-finish-benefits-costs' => [
    'title'       => 'Acrylic Finish for Home Interiors: Benefits, Costs & Real Solutions',
    'seo_title'   => 'Acrylic Finish: Benefits and Costs',
    'description' => 'Complete guide to acrylic finish for home interiors — types, brands, costs, kitchen & wardrobe applications, acrylic vs laminate vs PU vs membrane vs glass…',
    'category'    => 'Materials',
    'pillar'      => 'materials',
    'folder'      => 'acrylic-finish-benefits-costs',
    'hero_alt'    => 'Acrylic Finish for Home Interiors: Benefits, Costs & Real Solutions',
    'date'        => '2026-06-18',
    'updated'     => '2026-10-04',
    'canonical'   => '/materials/acrylic-finish/',
  ],
  'veneer-finish-luxury-wood-guide' => [
    'title'       => 'Veneer Finish for Home Interiors: The Ultimate Luxury Wood Guide (2026)',
    'seo_title'   => 'Veneer Finish: Luxury Wood Guide (2026)',
    'description' => 'Wood veneer for home interiors: species, cutting and matching, grades, polish, cost, durability and how to choose veneer for a luxury finish.',
    'category'    => 'Materials',
    'pillar'      => 'materials',
    'folder'      => 'veneer-finish-luxury-wood-guide',
    'hero_alt'    => 'Veneer Finish for Home Interiors: The Ultimate Luxury Wood Guide (2026)',
    'date'        => '2026-06-25',
    'updated'     => '2026-10-04',
    'canonical'   => '/materials/wood-veneer/',
  ],
  'hdhmr-board-carpenter-guide' => [
    'title'       => 'HDHMR Board for Interiors: A Carpenter\'s Honest Guide, and When Not to Use It',
    'seo_title'   => 'HDHMR Board: A Carpenter\'s Honest Guide',
    'description' => 'HDHMR board from a carpenter\'s view: how it is made, 2026 prices, brands, spotting fakes, installation and the places you should not use it.',
    'category'    => 'Materials',
    'pillar'      => 'materials',
    'folder'      => 'hdhmr-board-carpenter-guide',
    'hero_alt'    => 'HDHMR Board for Interiors: A Carpenter\'s Honest Guide, and When Not to Use It',
    'date'        => '2026-06-26',
    'updated'     => '2026-10-04',
    'canonical'   => '/materials/hdhmr-board/',
  ],
  'interior-materials-a-to-z' => [
    'title'       => 'Interior Materials A–Z: The Complete Designer\'s Glossary',
    'seo_title'   => 'Interior Materials A–Z: The Complete Glossary',
    'description' => 'An A–Z glossary of interior materials, from acoustic panels to zellige tiles, with what each is, where it is used and what to watch for.',
    'category'    => 'Materials',
    'pillar'      => 'materials',
    'folder'      => 'interior-materials-a-to-z',
    'hero_alt'    => 'Interior Materials A–Z: The Complete Designer\'s Glossary',
    'date'        => '2026-06-11',
    'updated'     => '2026-10-04',
    'canonical'   => '/glossary/',
  ],
  'l-shape-modular-kitchen-designs' => [
    'title'       => 'L-Shape Modular Kitchen Designs: Colors, Layouts & Smart Space Ideas',
    'seo_title'   => 'L-Shape Modular Kitchen Designs 2026',
    'description' => 'L-shape modular kitchen designs: 12 colour themes, space-saving layouts, work zones, materials and costs for Indian homes, with ideas for small kitchens.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'l-shape-modular-kitchen-designs',
    'hero_alt'    => 'L-Shape Modular Kitchen Designs: Colors, Layouts & Smart Space Ideas',
    'date'        => '2026-06-30',
    'updated'     => '2026-10-04',
  ],
  'u-shape-kitchen-designs' => [
    'title'       => 'U-Shape Kitchen Designs: The Three-Wall Workflow Machine',
    'seo_title'   => 'U-Shape Kitchen Designs 2026',
    'description' => 'U-shape kitchen designs: workflow, storage and ergonomics, real dimensions, who it suits, U vs L vs island, corners, ventilation and costs.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'u-shape-kitchen-designs',
    'hero_alt'    => 'U-Shape Kitchen Designs: The Three-Wall Workflow Machine',
    'date'        => '2026-06-30',
    'updated'     => '2026-10-04',
  ],
  'modular-kitchen-planning-guide' => [
    'title'       => 'The Complete Modular Kitchen Planning Guide',
    'seo_title'   => 'The Complete Modular Kitchen Guide 2026',
    'description' => 'The complete modular kitchen planning guide: layouts, materials, platforms, lighting, ventilation, storage and hardware, and mistakes to avoid.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'modular-kitchen-planning-guide',
    'hero_alt'    => 'The Complete Modular Kitchen Planning Guide',
    'date'        => '2026-06-10',
    'updated'     => '2026-10-04',
    'canonical'   => '/modular-kitchen/',
  ],
  'kitchen-storage-solutions-guide' => [
    'title'       => 'Kitchen Storage Solutions: The Definitive Guide for Every Home & Budget',
    'seo_title'   => 'Kitchen Storage Solutions',
    'description' => 'Kitchen storage solutions for every home and budget: cabinet types, drawer systems, organisers and need-based recommendations for Indian kitchens.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'kitchen-storage-solutions-guide',
    'hero_alt'    => 'Kitchen Storage Solutions: The Definitive Guide for Every Home & Budget',
    'date'        => '2026-06-16',
    'updated'     => '2026-10-04',
    'canonical'   => '/modular-kitchen/storage-solutions/',
  ],
  'modular-kitchen-storage-units-explained' => [
    'title'       => 'Modular Kitchen Storage: Every Unit, Accessory & Organizer — Explained with Real Costs',
    'seo_title'   => 'Modular Kitchen Storage: The Complete 2026 Guide',
    'description' => 'Every modular kitchen storage unit explained with 2026 prices: 18 storage types, accessories, organisers and how the big hardware brands compare.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'modular-kitchen-storage-units-explained',
    'hero_alt'    => 'Modular Kitchen Storage: Every Unit, Accessory & Organizer — Explained with Real Costs',
    'date'        => '2026-06-27',
    'updated'     => '2026-10-04',
    'canonical'   => '/modular-kitchen/storage-solutions/',
  ],
  'modular-kitchen-colour-pairings' => [
    'title'       => 'Modular Kitchen Colour Combinations: Best Pairings & 2026 Trends',
    'seo_title'   => 'Modular Kitchen Colour Combinations',
    'description' => 'Modular kitchen colour combinations: the best two-tone pairings, how colour changes a kitchen\'s size and light, and 2026 trends for Indian homes.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'modular-kitchen-colour-pairings',
    'hero_alt'    => 'Modular Kitchen Colour Combinations: Best Pairings & 2026 Trends',
    'date'        => '2026-06-20',
    'updated'     => '2026-10-04',
    'canonical'   => '/blogs/kitchen-colour-combinations/',
  ],
  'two-colour-kitchen-laminates' => [
    'title'       => 'Two-Colour Combinations for Kitchen Laminates That Work in Indian Homes',
    'seo_title'   => 'Two Color Combinations for Kitchen Laminates',
    'description' => 'Ten two-colour kitchen laminate palettes with swatches, pros, cons and a match matrix by kitchen size and light, for Indian homes.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'two-colour-kitchen-laminates',
    'hero_alt'    => 'Two-Colour Combinations for Kitchen Laminates That Work in Indian Homes',
    'date'        => '2026-06-25',
    'updated'     => '2026-10-04',
    'canonical'   => '/blogs/kitchen-colour-combinations/',
  ],
  'japandi-wabi-sabi-meets-scandinavian' => [
    'title'       => 'Japandi Interior Design: Where Japanese Wabi-Sabi Meets Scandinavian Hygge',
    'seo_title'   => 'Japandi Interior Design',
    'description' => 'Japandi interior design: Japanese wabi-sabi meets Scandinavian hygge. Colours, furniture, materials, principles and sourcing for Indian homes.',
    'category'    => 'Styles',
    'pillar'      => 'styles',
    'folder'      => 'japandi-wabi-sabi-meets-scandinavian',
    'hero_alt'    => 'Japandi Interior Design: Where Japanese Wabi-Sabi Meets Scandinavian Hygge',
    'date'        => '2026-06-20',
    'updated'     => '2026-10-04',
    'canonical'   => '/styles/japandi/',
  ],
  'minimalist-home-design-ideas' => [
    'title'       => 'Minimalist Home Design: The Complete Guide',
    'seo_title'   => 'Minimalist Home Design: The Complete Guide (2026)',
    'description' => 'Minimalist home design: philosophy, colours, materials, room-by-room ideas, real Bangalore costs, maintenance and honest pros and cons.',
    'category'    => 'Styles',
    'location'    => 'Bangalore',
    'pillar'      => 'styles',
    'folder'      => 'minimalist-home-design-ideas',
    'hero_alt'    => 'Minimalist Home Design: The Complete Guide',
    'date'        => '2026-07-03',
    'updated'     => '2026-10-04',
    'canonical'   => '/styles/minimalist/',
  ],
  'contemporary-living-india' => [
    'title'       => 'The Art of Contemporary Living — Designed for India',
    'seo_title'   => 'Contemporary Interior Design for Indian Homes',
    'description' => 'Contemporary interior design for Indian homes in 2026: colour palettes, room-by-room tips, materials and Indian fusion elements.',
    'category'    => 'Styles',
    'pillar'      => 'styles',
    'folder'      => 'contemporary-living-india',
    'hero_alt'    => 'The Art of Contemporary Living — Designed for India',
    'date'        => '2026-06-13',
    'updated'     => '2026-10-04',
    'canonical'   => '/styles/contemporary/',
  ],
  'choosing-an-interior-designer-checklist' => [
    'title'       => 'How to Choose an Interior Designer: The Complete Homeowner\'s Guide (2026)',
    'seo_title'   => 'How to Choose an Interior Designer',
    'description' => 'How to choose an interior designer: types of firms, portfolios, quotations, contracts, red flags and a checklist for Indian homeowners.',
    'category'    => 'Planning',
    'pillar'      => 'planning',
    'folder'      => 'choosing-an-interior-designer-checklist',
    'hero_alt'    => 'How to Choose an Interior Designer: The Complete Homeowner\'s Guide (2026)',
    'date'        => '2026-06-19',
    'updated'     => '2026-10-04',
    'canonical'   => '/planning/how-to-choose-interior-designer/',
  ],
  'vastu-for-home-interiors-room-by-room' => [
    'title'       => 'Ultimate Vastu Guide for Home Interiors: Room-by-Room Planning',
    'seo_title'   => 'Ultimate Vastu Guide for Home Interiors',
    'description' => 'Complete Vastu Shastra guide for home interiors — room-by-room planning for positive energy, modern solutions, and practical Vastu remedies without demolition.',
    'category'    => 'Vastu',
    'pillar'      => 'vastu',
    'folder'      => 'vastu-for-home-interiors-room-by-room',
    'hero_alt'    => 'Ultimate Vastu Guide for Home Interiors: Room-by-Room Planning',
    'date'        => '2026-08-29',
    'updated'     => '2026-10-04',
    'canonical'   => '/vastu/',
  ],
  'best-interior-designers-hyderabad' => [
    'title'       => 'The Best Interior Designers in Hyderabad, Sorted the Way Buyers Actually Shop',
    'seo_title'   => 'Best Interior Designers in Hyderabad 2026',
    'description' => 'How to choose among Hyderabad\'s interior designers: architect-led studios, luxury specialists and turnkey firms compared, with costs and questions to ask.',
    'category'    => 'Designers',
    'pillar'      => 'planning',
    'folder'      => 'best-interior-designers-hyderabad',
    'hero_alt'    => 'The Best Interior Designers in Hyderabad, Sorted the Way Buyers Actually Shop',
    'date'        => '2026-07-02',
    'updated'     => '2026-10-04',
  ],
  'best-interior-designers-pune' => [
    'title'       => 'The Best Interior Designers in Pune, Chosen for the City They Have to Survive',
    'seo_title'   => 'Best Interior Designers in Pune 2026',
    'description' => 'How to choose an interior designer in Pune: architect-led studios, factory-direct turnkey firms and boutique specialists compared, with costs and checks.',
    'category'    => 'Designers',
    'pillar'      => 'planning',
    'folder'      => 'best-interior-designers-pune',
    'hero_alt'    => 'The Best Interior Designers in Pune, Chosen for the City They Have to Survive',
    'date'        => '2026-07-02',
    'updated'     => '2026-10-04',
  ],
  'top-interior-designers-bangalore' => [
    'title'       => 'Top 20 Best Interior Designers in Bangalore — Ranked & Compared',
    'seo_title'   => 'Top Interior Designers in Bangalore (2026)',
    'description' => 'How Bangalore\'s interior design firms compare: national platforms, factory-backed firms and boutique studios, with prices, strengths and questions to ask.',
    'category'    => 'Designers',
    'location'    => 'Bangalore',
    'pillar'      => 'planning',
    'folder'      => 'top-interior-designers-bangalore',
    'hero_alt'    => 'Top 20 Best Interior Designers in Bangalore — Ranked & Compared',
    'date'        => '2026-06-23',
    'updated'     => '2026-10-04',
  ],
  /* MIGRATED-END */

  'kitchen-colour-combinations' => [
    'title'       => 'Two-Colour Kitchen Combinations That Work in Indian Homes',
    'seo_title'   => 'Kitchen Colour Combinations: 10 Two-Tone Ideas',
    'description' => 'Ten two-colour kitchen laminate combinations with swatches and hex codes, a decision table by kitchen size and light, finish advice and the mistakes to avoid.',
    'category'    => 'Kitchen',
    'location'    => 'Bangalore',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'kitchen-colour-combinations',
    'hero_alt'    => 'Two-colour modular kitchen with warm white wall units and walnut base units',
    'date'        => '2026-10-03',
  ],

  /* NEW-POSTS-START — added 2026-10-05: kitchen, living, wardrobe and South-East Bengaluru posts */
  'modular-kitchen-cost-electronic-city' => [
    'title'       => 'Modular Kitchen Cost in Electronic City: 2026 Prices by Layout and Finish',
    'seo_title'   => 'Modular Kitchen Cost in Electronic City (2026)',
    'description' => 'What a modular kitchen costs in Electronic City in 2026: L, parallel and U-shape prices by grade, what moves the price, hard-water extras and a local checklist.',
    'category'    => 'Kitchen',
    'location'    => 'Electronic City',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'modular-kitchen-cost-electronic-city',
    'hero_alt'    => 'L-shape modular kitchen in an Electronic City apartment with laminate base units and a quartz top',
    'date'        => '2026-10-05',
  ],
  'modular-kitchen-designs-chandapura' => [
    'title'       => '12 Modular Kitchen Designs That Fit Chandapura Homes',
    'seo_title'   => 'Modular Kitchen Designs for Chandapura Homes',
    'description' => 'Twelve modular kitchen designs for Chandapura flats, villas and independent houses: layouts, colour pairs, storage and the right board for each, with costs.',
    'category'    => 'Kitchen',
    'location'    => 'Chandapura',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'modular-kitchen-designs-chandapura',
    'hero_alt'    => 'Parallel modular kitchen with sage green base units in a Chandapura home',
    'date'        => '2026-10-05',
  ],
  '2-bhk-interiors-bommasandra' => [
    'title'       => '2 BHK Interiors in Bommasandra: Budget, Layout and a 60-Day Plan',
    'seo_title'   => '2 BHK Interiors in Bommasandra: Budget & Plan',
    'description' => 'Plan 2 BHK interiors in Bommasandra and Hebbagodi: room-by-room budget for 2026, storage for compact flats, materials for dust and humidity, and a 60-day plan.',
    'category'    => 'Local Guide',
    'location'    => 'Bommasandra',
    'pillar'      => 'cost',
    'folder'      => '2-bhk-interiors-bommasandra',
    'hero_alt'    => 'Compact 2 BHK apartment living room and kitchen in Bommasandra',
    'date'        => '2026-10-05',
  ],
  'living-room-ideas-electronic-city-apartments' => [
    'title'       => 'Living Room Ideas for Electronic City Apartments: 15 Looks That Work',
    'seo_title'   => 'Living Room Ideas for Electronic City Flats',
    'description' => 'Fifteen living room ideas for Electronic City apartments: TV walls, ceilings, colour palettes, seating layouts, heat and dust control, with indicative costs.',
    'category'    => 'Living',
    'location'    => 'Electronic City',
    'pillar'      => 'rooms',
    'folder'      => 'living-room-ideas-electronic-city-apartments',
    'hero_alt'    => 'Warm contemporary living room in an Electronic City apartment with a fluted TV wall',
    'date'        => '2026-10-05',
  ],
  'tv-unit-wall-designs-bangalore' => [
    'title'       => 'TV Unit Wall Designs for Bangalore Living Rooms: 12 Ideas with Costs',
    'seo_title'   => 'TV Unit Wall Designs: 12 Ideas with Costs',
    'description' => 'Twelve TV unit wall designs for Bangalore living rooms, from laminate panels to fluted and stone-look walls, with sizes, wiring tips and 2026 costs.',
    'category'    => 'Living',
    'location'    => 'Bangalore',
    'pillar'      => 'furniture',
    'folder'      => 'tv-unit-wall-designs-bangalore',
    'hero_alt'    => 'Floating TV unit on a walnut panel wall with open niches and cove lighting',
    'date'        => '2026-10-05',
  ],
  'parallel-kitchen-designs' => [
    'title'       => 'Parallel Kitchen Designs for Narrow Indian Kitchens',
    'seo_title'   => 'Parallel Kitchen Designs for Narrow Kitchens',
    'description' => 'Parallel (galley) kitchen designs for narrow Indian kitchens: aisle widths, what goes on each run, storage, lighting, colour ideas and 2026 costs.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'parallel-kitchen-designs',
    'hero_alt'    => 'Parallel modular kitchen with the hob on one run and the sink on the other',
    'date'        => '2026-10-05',
  ],
  'small-kitchen-design-ideas' => [
    'title'       => 'Small Kitchen Design Ideas for 1 and 2 BHK Flats',
    'seo_title'   => 'Small Kitchen Design Ideas for Indian Flats',
    'description' => 'Small kitchen ideas for 1 and 2 BHK flats: layouts, storage to the ceiling, compact appliances, light colours and lighting, with sizes and costs that work.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'small-kitchen-design-ideas',
    'hero_alt'    => 'Compact straight modular kitchen with lofts and light laminate shutters',
    'date'        => '2026-10-05',
  ],
  'wardrobe-designs-small-bedrooms' => [
    'title'       => 'Wardrobe Designs for Small Bedrooms: 10 Space-Saving Ideas',
    'seo_title'   => 'Wardrobe Designs for Small Bedrooms',
    'description' => 'Ten wardrobe designs for small bedrooms: sliding doors, corner units, lofts, mirror shutters, shallow wardrobes and bed-side storage, with sizes and costs.',
    'category'    => 'Wardrobes',
    'pillar'      => 'wardrobe',
    'folder'      => 'wardrobe-designs-small-bedrooms',
    'hero_alt'    => 'Sliding wardrobe with a mirror door in a small bedroom',
    'date'        => '2026-10-05',
  ],
  'kitchen-chimney-hob-guide' => [
    'title'       => 'Kitchen Chimney and Hob: How to Choose for Indian Cooking',
    'seo_title'   => 'Kitchen Chimney and Hob Buying Guide',
    'description' => 'Choose a kitchen chimney and hob for Indian cooking: suction, filters, auto-clean, ducting, burner types, glass vs steel, sizes, placement and prices.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'kitchen-chimney-hob-guide',
    'hero_alt'    => 'Wall-mounted kitchen chimney above a four-burner glass hob',
    'date'        => '2026-10-05',
  ],
  'modular-kitchen-mistakes' => [
    'title'       => '15 Modular Kitchen Mistakes Bangalore Homeowners Regret',
    'seo_title'   => '15 Modular Kitchen Mistakes to Avoid',
    'description' => 'Fifteen modular kitchen mistakes Bangalore homeowners regret, from the wrong board under the sink to too few sockets, and how to avoid each before you order.',
    'category'    => 'Kitchen',
    'location'    => 'Bangalore',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'modular-kitchen-mistakes',
    'hero_alt'    => 'Modular kitchen with a swollen sink cabinet beside a correctly built one',
    'date'        => '2026-10-05',
  ],
  'factory-made-vs-site-made-interiors' => [
    'title'       => 'Factory-Made vs Site-Made Interiors: What Changes for You',
    'seo_title'   => 'Factory-Made vs Site-Made Interiors',
    'description' => 'Factory-made modular interiors vs site-made carpentry: finish, durability, time, dust, cost and repairs compared, and what to check on a factory visit.',
    'category'    => 'Planning',
    'pillar'      => 'planning',
    'folder'      => 'factory-made-vs-site-made-interiors',
    'hero_alt'    => 'Panel saw and edge-banding machine in a modular furniture factory',
    'date'        => '2026-10-05',
  ],
  'kitchen-living-partition-ideas' => [
    'title'       => 'Kitchen-to-Living Partition Ideas for Open and Semi-Open Kitchens',
    'seo_title'   => 'Kitchen Partition Ideas: Open & Semi-Open',
    'description' => 'Partition ideas between kitchen and living room: glass, fluted glass, breakfast counters, sliding doors and jaali, with smoke control, sizes and costs.',
    'category'    => 'Kitchen',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'kitchen-living-partition-ideas',
    'hero_alt'    => 'Fluted glass sliding partition between an open kitchen and a dining area',
    'date'        => '2026-10-05',
  ],
  'living-dining-layout-2-bhk' => [
    'title'       => 'Living and Dining Layouts for 2 BHK Apartments: 8 Plans That Work',
    'seo_title'   => 'Living and Dining Layouts for 2 BHK Flats',
    'description' => 'Eight living and dining layouts for 2 BHK apartments: L-shaped halls, long halls, square halls and open kitchens, with clearances, furniture sizes and tips.',
    'category'    => 'Living',
    'pillar'      => 'rooms',
    'folder'      => 'living-dining-layout-2-bhk',
    'hero_alt'    => 'Floor plan of an L-shaped living and dining hall with furniture',
    'date'        => '2026-10-05',
  ],
  'false-ceiling-designs-living-room' => [
    'title'       => 'False Ceiling Designs for Living Rooms: 10 Ideas with Costs',
    'seo_title'   => 'Living Room False Ceiling Designs and Cost',
    'description' => 'Ten false ceiling designs for living rooms: peripheral, cove, tray, wooden rafter and floating ceilings, with heights, lighting and 2026 costs per sq ft.',
    'category'    => 'Living',
    'pillar'      => 'false-ceiling',
    'folder'      => 'false-ceiling-designs-living-room',
    'hero_alt'    => 'Living room with a peripheral gypsum false ceiling and warm cove lighting',
    'date'        => '2026-10-05',
  ],
  'rental-flat-interiors-electronic-city' => [
    'title'       => 'Furnishing a Rental Flat in Electronic City: A Landlord\'s Guide',
    'seo_title'   => 'Rental Flat Interiors in Electronic City',
    'description' => 'A landlord\'s guide to furnishing a rental flat in Electronic City: what tenants expect, durable materials, semi vs fully furnished budgets and rent payback.',
    'category'    => 'Local Guide',
    'location'    => 'Electronic City',
    'pillar'      => 'cost',
    'folder'      => 'rental-flat-interiors-electronic-city',
    'hero_alt'    => 'Semi-furnished 2 BHK rental flat in Electronic City with a modular kitchen and wardrobes',
    'date'        => '2026-10-05',
  ],
  'new-flat-interior-timeline-chandapura' => [
    'title'       => 'From Handover to Move-In: Interior Timeline for New Flats in Chandapura',
    'seo_title'   => 'New Flat Interior Timeline: Handover to Move-In',
    'description' => 'A week-by-week interior timeline for new flats in Chandapura and Electronic City, from builder handover and snag list to design, factory, installation and move-in.',
    'category'    => 'Planning',
    'location'    => 'Chandapura',
    'pillar'      => 'planning',
    'folder'      => 'new-flat-interior-timeline-chandapura',
    'hero_alt'    => 'New apartment under interior work with modules being installed',
    'date'        => '2026-10-05',
  ],
  'pooja-unit-designs-small-apartments' => [
    'title'       => 'Pooja Unit Designs for Small Apartments: Wall, Corner and Cabinet Ideas',
    'seo_title'   => 'Pooja Unit Designs for Small Apartments',
    'description' => 'Pooja unit designs for small apartments: wall-mounted, corner, cabinet and niche ideas, with sizes, materials, doors, lighting, vastu notes and costs.',
    'category'    => 'Pooja Room',
    'pillar'      => 'rooms',
    'folder'      => 'pooja-unit-designs-small-apartments',
    'hero_alt'    => 'Wall-mounted wooden pooja unit with jaali doors and a back-lit panel',
    'date'        => '2026-10-05',
  ],
  'monsoon-proof-kitchen-wardrobe' => [
    'title'       => 'Monsoon-Proof Interiors: Protecting Kitchens and Wardrobes from Humidity',
    'seo_title'   => 'Monsoon-Proof Kitchens and Wardrobes',
    'description' => 'Protect kitchens and wardrobes from Bangalore\'s monsoon humidity: the right boards, edge sealing, ventilation, damp walls, fittings and a seasonal care routine.',
    'category'    => 'Materials',
    'location'    => 'Bangalore',
    'pillar'      => 'materials',
    'folder'      => 'monsoon-proof-kitchen-wardrobe',
    'hero_alt'    => 'Close-up of a sealed plywood edge on a kitchen sink cabinet',
    'date'        => '2026-10-05',
  ],
  '3-bhk-interiors-electronic-city' => [
    'title'       => '3 BHK Interiors near Electronic City: Room-by-Room Budget for 2026',
    'seo_title'   => '3 BHK Interiors near Electronic City: Budget',
    'description' => 'Room-by-room 3 BHK interior budget for homes near Electronic City and Chandapura in 2026: kitchen, wardrobes, living, ceilings and what to do in phases.',
    'category'    => 'Cost',
    'location'    => 'Electronic City',
    'pillar'      => 'cost',
    'folder'      => '3-bhk-interiors-electronic-city',
    'hero_alt'    => 'Living and dining area of a 3 BHK apartment near Electronic City',
    'date'        => '2026-10-05',
  ],
  'wardrobe-with-dressing-unit-ideas' => [
    'title'       => 'Wardrobe with Dressing Unit: 10 Ideas for Master Bedrooms',
    'seo_title'   => 'Wardrobe with Dressing Unit Design Ideas',
    'description' => 'Ten ideas for a wardrobe with a built-in dressing unit: mirror shutters, pull-out mirrors, vanity bays, lighting, sizes and costs for master bedrooms.',
    'category'    => 'Wardrobes',
    'pillar'      => 'wardrobe',
    'folder'      => 'wardrobe-with-dressing-unit-ideas',
    'hero_alt'    => 'Wardrobe wall with a built-in dressing table, lit mirror and drawers',
    'date'        => '2026-10-05',
  ],
  /* NEW-POSTS-END */

  /* Examples — copy one, change the slug and details, then create the matching file in /blogs/
  'l-shape-modular-kitchen-designs' => [
    'title'       => 'L-Shape Modular Kitchen Designs',
    'description' => '...',
    'category'    => 'Kitchen',
    'location'    => 'Bangalore',
    'pillar'      => 'modular-kitchen',
    'folder'      => 'l-shape-modular-kitchen-designs',
    'hero_alt'    => 'L-shape modular kitchen design in Bangalore',
    'date'        => '2026-10-03',
  ],
  'sliding-wardrobe-designs' => [
    'title'       => 'Sliding Wardrobe Designs for Bedrooms',
    'description' => '...',
    'category'    => 'Wardrobes',
    'pillar'      => 'wardrobe',
    'folder'      => 'sliding-wardrobe-designs',
    'hero_alt'    => 'Modern sliding wardrobe design for bedroom',
    'date'        => '2026-10-03',
  ],
  'pooja-room-designs' => [
    'title'       => 'Pooja Room Designs for Indian Homes',
    'description' => '...',
    'category'    => 'Pooja Room',
    'pillar'      => 'rooms',
    'folder'      => 'pooja-room-designs',
    'hero_alt'    => 'Wooden pooja room design with jaali doors',
    'date'        => '2026-10-03',
  ],
  */
];

/* ---------- helpers (no need to edit) ---------- */
const BLOG_BASE = '/blogs';
function post_url($slug) { return BLOG_BASE . '/' . $slug . '/'; }

// Posts that have a file and are not drafts (drafts show on staging), newest first.
// Optional filters: category name, pillar key, how many.
function posts($category = null, $pillar = null, $limit = null) {
  global $POSTS;
  $out = [];
  foreach ($POSTS as $slug => $p) {
    if (!is_file(rtrim($_SERVER['DOCUMENT_ROOT'], '/') . BLOG_BASE . '/' . $slug . '.php')) continue;
    if (!empty($p['draft']) && !is_staging()) continue;
    if ($category && strcasecmp($p['category'], $category) !== 0) continue;
    if ($pillar && ($p['pillar'] ?? '') !== $pillar) continue;
    $out[$slug] = $p + ['slug' => $slug, 'url' => post_url($slug)];
  }
  uasort($out, fn($a, $b) => strcmp($b['date'], $a['date']));
  return $limit ? array_slice($out, 0, $limit, true) : $out;
}
